### ISSUE TITLE
我想评论一下都不行呢，，，

### ISSUE THREAD

**Issue by Niracler** [allenxz/allenxz.github.io#1]
或许你可以试一下这个 [gittalk](https://github.com/gitalk/gitalk)

是一个基于 Github Issue 和 Preact 开发的评论插件

![screenshot_20181220_153233](https://user-images.githubusercontent.com/24842631/50270600-0d253780-046d-11e9-864d-4c11b8c7c3e1.png)

**Comment by allenxz** [comment]
欧克欧克 放假弄一下 原本就想弄的· 一直耽搁了
