### ISSUE TITLE
算法题解 – 阿政 | Allen Tan

### ISSUE THREAD

**Issue by allenxz** [allenxz/allenxz.github.io#14]
https://allenxz.github.io/%E7%AE%97%E6%B3%95%E9%A2%98%E8%A7%A3/ 

 阿政的博客

**Comment by DayDreamYH** [comment]
感觉最低点，入不敷出没理解大盘，能get到最低点但是不知道为什么最低点的下一个就是必然成功的开始点

**Comment by allenxz** [comment]
> @DayDreamYH
> 感觉最低点，入不敷出没理解大盘，能get到最低点但是不知道为什么最低点的下一个就是必然成功的开始点

因为找到最低点前的那些点，尤其是最低点，都是一步一步在加深入不敷出的程度，而从最低点到其下一点反而是扭转了这种状况。将最低点的下一点作为起点，代表这种路径把这些“难啃的骨头”放在了后半段，就能在路径的前半段积攒更多的油，从而完成绕行
